use vein;
CREATE TABLE `PERSON` (
	   `ID` varchar(36) NOT NULL,
	   `IDCARD` varchar(18) DEFAULT NULL,
	   `NAME` varchar(20) DEFAULT NULL,
	   `SEX` varchar(4) DEFAULT NULL,
	   `NATION` varchar(10) DEFAULT NULL,
	   `BIRTHDAY` varchar(10) DEFAULT NULL,
	   `IDCARD_START_DATE` varchar(10) DEFAULT NULL,
	   `IDCARD_END_DATE` varchar(10) DEFAULT NULL,
	   `VISAPLACE` varchar(50) DEFAULT NULL,
	   `IDCARD_ADDRESS` varchar(100) DEFAULT NULL,
	   `IDCARDPHOTOURI` longtext,
	   `PHOTOURI` varchar(100) DEFAULT NULL,
	   `IDCARD_CREDIBILITY` varchar(2) DEFAULT NULL,
	   `EMPLOYEE_ID` varchar(36) DEFAULT NULL,
	   `CELLPHONE` varchar(15) DEFAULT NULL,
	   `CARDID` varchar(50) DEFAULT NULL,
	   `ETAG` varchar(36) NOT NULL,
	   PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
alter table VEIN rename DEVICE;
alter table DEVICE add ETAG varchar(36) DEFAULT NULL;
alter table DEVICE add deleted_at datetime DEFAULT NULL;
INSERT INTO vein.PERSON (ID, IDCARD, NAME, SEX, CELLPHONE, EMPLOYEE_ID, ETAG) select ID, IDCARD, NAME, SEX_CD, CELLPHONE,EMPLOYEE_ID,'0' from enterprise.USER where ISDELETE='1';
INSERT INTO enterprise.FEATURE(ID, USER_ID, FINGER) select ID, PERSON_ID, FINGER from vein.FEATURE where PERSON_TYPE='user';
