version: '2'
services:
  web:
    image: daocloud.io/muninn/web:c_yangling
    ports:
    - ${WEB_PORT}:80
    environment:
    - API_URL=http://${IP}:${API_PORT}/
    - USABLE=enterprise_access_attendance_exam_payment_core
    depends_on:
    - gateway
    restart: unless-stopped
  gateway:
    image: daocloud.io/muninn/gateway:c_yangling
    ports:
    - ${API_PORT}:80
    depends_on:
    - enterprise
    - access
    - attendance
    - exam
    - payment
    - veincore
    restart: unless-stopped
  enterprise:
    image: daocloud.io/muninn/enterprise:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - EPCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veincore:
    image: daocloud.io/muninn/veincore:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - VCCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  access:
    image: daocloud.io/muninn/access:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - ACCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  attendance:
    image: daocloud.io/muninn/attendance:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - ATCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  exam:
    image: daocloud.io/muninn/exam:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - EACONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  payment:
    image: daocloud.io/muninn/payment:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - PMCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  padadapter:
    image: daocloud.io/muninn/padadapter:c_yangling
    ports:
    - ${PAD_PORT}:9789
    restart: unless-stopped
  poscontroller:
    image: daocloud.io/muninn/poscontroller:c_yangling
    ports:
    - ${POS_PORT}:9090/udp
    environment:
    - PCCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  minio:
    image: daocloud.io/muninn/minio
    environment:
    - MINIO_ACCESS_KEY=shengdian
    - MINIO_SECRET_KEY=xianshengdianshijikejiyouxiangongsi
    volumes:
    - /home/ubuntu/minio/export:/export
    - /home/ubuntu/minio/config:/root/.minio
    ports:
    - ${OSS_PORT}:9000
    restart: unless-stopped
    command: server /export
  minioadapter:
    image: daocloud.io/muninn/minioadapter:c_yangling
    environment:
    - MACONFIG_DEBUG=true
    - MACONFIG_ENDPOINT=${IP}:${OSS_PORT}
    restart: unless-stopped
  veinlistener:
    image: daocloud.io/muninn/veinlistener:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VLCONFIG_DEBUG=${DEBUG}
    ports:
    - ${VEIN_PORT}:9022
    restart: unless-stopped
  doorcontroller:
    image: daocloud.io/muninn/doorcontroller:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - DCCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veinverification:
    image: daocloud.io/muninn/veinverification:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VVCONFIG_SECURITY=${VEIN_SECURITY}
    - VVCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veinenrollment:
    image: daocloud.io/muninn/veinenrollment:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VECONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  mysql:
    image: mysql:5.7.16
    ports:
    - ${DB_PORT}:3306
    volumes:
    - /home/ubuntu/mysql_data/yangling:/var/lib/mysql
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${MQ_PORT}:15672
    hostname: yangling-rabbit
    restart: unless-stopped
  redis:
    image: redis:3
    restart: unless-stopped
