version: '2'
services:
  web:
    image: daocloud.io/muninn/web:c_guodian
    ports:
    - ${WEB_PORT}:80
    environment:
    - API_URL=http://${IP}:${API_PORT}/
    - USABLE=enterprise_access_core_visitor
    depends_on:
    - gateway
    restart: unless-stopped
  gateway:
    image: daocloud.io/muninn/gateway:c_guodian
    ports:
    - ${API_PORT}:80
    depends_on:
    - enterprise
    - access
    - veincore
    - visitor  
    restart: unless-stopped
  enterprise:
    image: daocloud.io/muninn/enterprise:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - EPCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veincore:
    image: daocloud.io/muninn/veincore:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - VCCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  access:
    image: daocloud.io/muninn/access:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - ACCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  padadapter:
    image: daocloud.io/muninn/padadapter:c_guodian
    ports:
    - ${PAD_PORT}:9789
    restart: unless-stopped
  minio:
    image: daocloud.io/muninn/minio
    environment:
    - MINIO_ACCESS_KEY=shengdian
    - MINIO_SECRET_KEY=xianshengdianshijikejiyouxiangongsi
    volumes:
    - /home/ubuntu/minio/export:/export
    - /home/ubuntu/minio/config:/root/.minio
    ports:
    - ${OSS_PORT}:9000
    restart: unless-stopped
    command: server /export
  minioadapter:
    image: daocloud.io/muninn/minioadapter:c_guodian
    environment:
    - MACONFIG_DEBUG=true
    - MACONFIG_ENDPOINT=${IP}:${OSS_PORT}
    restart: unless-stopped
  veinlistener:
    image: daocloud.io/muninn/veinlistener:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VLCONFIG_DEBUG=${DEBUG}
    ports:
    - ${VEIN_PORT}:9022
    restart: unless-stopped
  doorcontroller:
    image: daocloud.io/muninn/doorcontroller:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - DCCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veinverification:
    image: daocloud.io/muninn/veinverification:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VVCONFIG_SECURITY=${VEIN_SECURITY}
    - VVCONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  veinenrollment:
    image: daocloud.io/muninn/veinenrollment:c_guodian
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VECONFIG_DEBUG=${DEBUG}
    restart: unless-stopped
  mysql:
    image: mysql:5.7.16
    ports:
    - ${DB_PORT}:3306
    environment:
    - TZ=Asia/Shanghai
    volumes:
    - /home/ubuntu/mysql_data/guodian:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${MQ_PORT}:15672
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 25672:25672 
    hostname: guodian-rabbit
    restart: unless-stopped
  redis:
    image: redis:3
    restart: unless-stopped
  posprinter:
    image: daocloud.io/muninn/posprinter:c_guodian
    environment:
    - PP_OSS_URL=minio:9000
    restart: unless-stopped
