version: '2'
services:
  web:
    image: daocloud.io/muninn/web:c_yangling
    ports:
    - 80:80
    environment:
    - API_URL=http://${IP}:8010/
    depends_on:
    - gateway
    restart: always
  gateway:
    image: daocloud.io/muninn/gateway:c_yangling
    ports:
    - 8010:80
    depends_on:
    - enterprise
    - device
    - access
    - attendance
    restart: always
  enterprise:
    image: daocloud.io/muninn/enterprise:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - EPCONFIG_DEBUG=true
    restart: always
  device:
    image: daocloud.io/muninn/device:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - DECONFIG_DEBUG=true
    restart: always
  access:
    image: daocloud.io/muninn/access:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - ACCONFIG_DEBUG=true
    restart: always
  attendance:
    image: daocloud.io/muninn/attendance:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    - redis
    environment:
    - ATCONFIG_DEBUG=true
    restart: always
  veinlistener:
    image: daocloud.io/muninn/veinlistener:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VLCONFIG_DEBUG=true
    ports:
    - 9044:9022
    restart: always
  doorcontroller:
    image: daocloud.io/muninn/doorcontroller:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - DCCONFIG_DEBUG=true
    restart: always
  veinverification:
    image: daocloud.io/muninn/veinverification:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VVCONFIG_SECURITY=2
    - VVCONFIG_DEBUG=true
    restart: always
  veinenrollment:
    image: daocloud.io/muninn/veinenrollment:c_yangling
    depends_on:
    - mysql
    - rabbitmq
    environment:
    - VECONFIG_DEBUG=true
    restart: always
  mysql:
    image: mysql
    ports:
    - 3312:3306
    volumes:
    - /home/ubuntu/mysql_data/yangling:/var/lib/mysql
    restart: always
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 15674:15672
    hostname: yangling-rabbit
    restart: always
  redis:
    image: redis
    restart: always

