ALTER TABLE `vein`.`VEIN` CHANGE COLUMN `ISCOLLECT` `ISCOLLECT` char(1) NOT NULL DEFAULT '1', ADD COLUMN `ISATTENDANCE` char(1) NOT NULL DEFAULT '1' COMMENT '' AFTER `ISCOLLECT`;
TRUNCATE TABLE `attendance`.`RECORD`;
TRUNCATE TABLE `attendance`.`TASK_RECORD`;
TRUNCATE TABLE `attendance`.`REPORT_FORM_DYNAMIC`;
TRUNCATE TABLE `attendance`.`REPORT_FORM`;
