docker load -i images/web.tar.gz
docker load -i images/gateway.tar.gz
docker load -i images/doorcontroller.tar.gz
docker load -i images/veinverification.tar.gz
docker load -i images/access.tar.gz
docker load -i images/veinenrollment.tar.gz
docker load -i images/device.tar.gz
docker load -i images/veinlistener.tar.gz
docker load -i images/enterprise.tar.gz
docker load -i images/attendance.tar.gz
docker load -i images/mysql.tar.gz
docker load -i images/redis.tar.gz
